### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by dizda** [nbobtc/BitcoindBundle#5]
Would be great if you set tags after merging/pushing.

1.0.0
1.0.1

and so on..

0.0.X+1 = BugFix
0.X+1.0 = Feature
X+1.0.0 = Code Break

What do you think ?

**Comment by JoshuaEstes** [comment]
Agree, semver.org. I'll try to remember to tag when doing merge requests and such.

**Comment by dizda** [comment]
That's cool, thanks :)
